name: NOAH DISPLAY
favicon: null
layout_spectrum: 0.25525
typography_spectrum: 0.31481
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0.8120836191810668
purpose: []
