name: Noahdisplay
favicon: null
layout_spectrum: 0.2846383105497807
typography_spectrum: 0.1587871473748237
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9350687523838133
  lightness: 0.1501235463656485
  saturation: 0.848131678532809
  rhythmicContrast: 0.8120836191810668
purpose: []
